### ISSUE TITLE
A question: batch size 6

### ISSUE THREAD

**Issue by thusinh1969** [eps696/stargan2#2]
I managed to get an RTX3090 which has 16G. With Tensorflow version of Clovaai, I managed to get a batch size of 6 on dataset 512x512 (eats up 18G GPU) and still training as it run extremely slowly (and seems heavy) compares to StyleGan V2 on Pytorch.

What do you think of your codes on batch size 6 would it be worth trying? My dataset is purely indoor scene and furniture, close to million of images.

Anyhow, would you make your code work on multi GPUs, please ?

Thanks,
Steve

**Comment by eps696** [comment]
1) RTX 3090 has 24G RAM onboard, there's no model with 16G
2) you mentioned StyleGAN - did you mistype? this repo is about StarGAN 
3) batch 6 should be more or less ok, but i'm quite sceptic about size 512. this is written in the readme. 
4) default iteration count for this setup is ~100k; 300k usually leads to overfit (this is also in the readme). i'm not sure if 1M images here makes any sense. 
5) unfortunately, i'm not an expert in parallel processing, and have no plans to learn multi-GPU coding soon. 

UPD: i didn't manage to fit batch 6 of 512x512 on 3090 - maximum 5 with this code.
