### ISSUE TITLE
hi, which platform did you spread this repo?

### ISSUE THREAD

**Issue by shoutOutYangJie** [eps696/stargan2#3]
Do you broadcast this repo on Facebook or Reddit? I want to know how to access the wonderful repo for the first time.

**Comment by eps696** [comment]
thanks for your interest. 
i'm afraid, i didn't quite catch what you mean by "broadcasting the repo". if you're looking for some hands-on video-tutorials - i do not produce such things. 
there should be some practical generating scripts & colab notebooks added later on (hopefully within month or two). 
please bear in mind: this repo is not a "one-button" tool; one needs to train their own models to work with it. 
as such, it requires some level of generic familiarity with neural networks operation, data preparation, models training, etc. such info can be easily googled (there are tons of introductory articles and/or videos around).

**Comment by shoutOutYangJie** [comment]
sorry, I mean how let more people know that you create this repo? Which website do you choose to boardcast the GitHub repo?





------------------ Original ------------------
From: vadim epstein ***@***.***&gt;
Date: Thu,Jul 29,2021 2:50 PM
To: eps696/stargan2 ***@***.***&gt;
Cc: shoutOutYangJie ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [eps696/stargan2] hi, which platform did you spread this repo? (#3)





 
thanks for your interest.
 i'm afraid, i didn't quite catch what you mean by "broadcasting the repo". if you're looking for some hands-on video-tutorials - i do not produce such things.
 there should be some practical generating scripts &amp; colab notebooks added later on (hopefully within month or two).
 please bear in mind: this repo is not a "one-button" tool; one needs to train their own models to work with it.
 as such, it requires some level of generic familiarity with neural networks operation, data preparation, models training, etc. such info can be easily googled (there are tons of introductory articles and/or videos around).

**Comment by eps696** [comment]
i post on [facebook.com/eps696](https://facebook.com/eps696) and/or [twitter.com/eps696](https://twitter.com/eps696)

i'm quite curious then, how did _you_ find this repo, if you're not my reader? ::]

**Comment by eps696** [comment]
i guess, the question is addressed, so i'm closing the issue. feel free to reopen if needed.
