### ISSUE TITLE
How to run with pretrained celeba HQ ?

### ISSUE THREAD

**Issue by hdxpmc** [eps696/stargan2#5]
Hello,
Where to download pretrained celebA HQ to run with test.py ?

**Comment by eps696** [comment]
1) you can put the model anywhere, specifying the path to it with `--model` argument.
2) at the moment, this repo does not support high-pass filtering extension, which was used for original celebA HQ model.

**Comment by hdxpmc** [comment]
Can we use the pretrained model from stargan v2 (https://github.com/clovaai/stargan-v2)?

**Comment by eps696** [comment]
you can use afhq model, since it was trained without high pass filtering (`--w_hpf==0`)
